### ISSUE TITLE
I have tried many times, but I can't run through your TCN model. Please help me

### ISSUE THREAD

**Issue by lifepassion** [ABurrello/tcn-hard-disk-failure-prediction#3]
### That's my argument. I didn't know it wasn't correct

model = 'ST3000DM001'
years = ['2013','2014','2015','2016']
windowing = 1
min_days_HDD = 115
days_considered_as_failure = 7
test_train_perc = 0.3
oversample_undersample = 2
balancing_normal_failed = 20
history_signal = 32
classifier = 'TCN'

perform_features_extraction = False
CUDA_DEV = "0"

ranking = 'Ok'
num_features = 18
overlap = 1

**Comment by ABurrello** [comment]
Which error log do you have? the parameters seem correct.

**Comment by lifepassion** [comment]
**Thank you first of all for your answer**

Which technique should I use when I use TCN algorithm?
I set it to hdd ( technique='hdd' ) and the error at runtime is

![image](https://user-images.githubusercontent.com/55479511/217521248-d151747a-5415-4b85-b8ab-ae4b4e3f0e78.png)

The primary reason I found is because useless features are dropped in technique='random'

![image](https://user-images.githubusercontent.com/55479511/217521576-dc3e84bb-e68e-4787-81bc-daf1ed49611e.png)

But this step is not performed in technique='hdd' ，So that led to the error

![image](https://user-images.githubusercontent.com/55479511/217522055-e7fbfdad-db7e-411b-a0aa-c84fc7f9f4a0.png)

What can I do to avoid this error？
And  (random/hdd/temporal)
What are the specific differences between them? 

**Look forward to your reply. Thank you again**

**Comment by ABurrello** [comment]
Ok.
First, I suggest to use "random" as a technique. It is the one used in the paper. In HDD, the data are divided per HDD.
Second, when you define the history of the signal, you have to be sure that this number divides exactly the dataset dimension X.shape[1].
For instance, with
model = 'ST3000DM001'
years = ['2014','2015','2016','2017','2018']
a history = 90, works.
The problem is found in the first error you reported since you cannot reshape data given that the division is not exact.
Hope this helps.
Alessio
